kind: SeldonDeployment
metadata:
  name: ignored
spec:
  predictors:
    - graph:
        implementation: TRITON_SERVER
        logger:
          mode: all
        modelUri: gs://seldon-models/triton/pytorch_cifar10
        name: cifar10
        type: MODEL
      name: default
      replicas: 1
      componentSpecs:
        - spec:
            hostIPC: true
            securityContext:
              runAsUser: 1000
            containers:
              - name: cifar10
                resources:
                  limits:
                    nvidia.com/gpu-10gb: 1
            nodeSelector:
              accelerator: nvidia
            tolerations:
              - key: accelerator
                operator: Equal
                value: nvidia
                effect: NoSchedule
              - key: "kubernetes.azure.com/scalesetpriority"
                operator: "Equal"
                value: "spot"
                effect: "NoSchedule"

